services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agilehelper
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
volumes:
  pgdata:
