# Generated by Django 4.2.4 on 2023-09-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_is_organisator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_facilitator',
            field=models.BooleanField(default=False),
        ),
    ]
